version: 0.2

env:
  variables:
    NODE_ENV: production
    APP_ENV: production
phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Docker image..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/m5n9g3g9
      - docker build -t swiggy-pavan .
      - docker tag swiggy-pavan:latest public.ecr.aws/m5n9g3g9/swiggy-pavan:latest
      - docker push public.ecr.aws/m5n9g3g9/swiggy-pavan:latest
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: '.'  # This should be the directory where your build artifacts are located
  name: swiggy-build-artifact
  discard-paths: no