version: 0.2

env:
  variables:
    NODE_ENV: production
    APP_ENV: production
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login $DOCKER_REGISTRY_URL -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - docker build -t gpavankmarreddy/swiggy:latest .
      - docker images  # List images to verify build success
      - docker push --verbose gpavankmarreddy/swiggy:latest
  post_build:
    commands:
      - echo "Build completed successfully!"
